INSERT INTO country (id, code, name) VALUES ('004','AF','Afghanistan');
INSERT INTO country (id, code, name) VALUES ('248','AX','Åland Islands');
INSERT INTO country (id, code, name) VALUES ('008','AL','Albania');
INSERT INTO country (id, code, name) VALUES ('012','DZ','Algeria');
INSERT INTO country (id, code, name) VALUES ('016','AS','American Samoa');
INSERT INTO country (id, code, name) VALUES ('020','AD','Andorra');
INSERT INTO country (id, code, name) VALUES ('024','AO','Angola');
INSERT INTO country (id, code, name) VALUES ('660','AI','Anguilla');
INSERT INTO country (id, code, name) VALUES ('010','AQ','Antarctica');
INSERT INTO country (id, code, name) VALUES ('028','AG','Antigua and Barbuda');
INSERT INTO country (id, code, name) VALUES ('032','AR','Argentina');
INSERT INTO country (id, code, name) VALUES ('051','AM','Armenia');
INSERT INTO country (id, code, name) VALUES ('533','AW','Aruba');
INSERT INTO country (id, code, name) VALUES ('036','AU','Australia');
INSERT INTO country (id, code, name) VALUES ('040','AT','Austria');
INSERT INTO country (id, code, name) VALUES ('031','AZ','Azerbaijan');
INSERT INTO country (id, code, name) VALUES ('044','BS','Bahamas');
INSERT INTO country (id, code, name) VALUES ('048','BH','Bahrain');
INSERT INTO country (id, code, name) VALUES ('050','BD','Bangladesh');
INSERT INTO country (id, code, name) VALUES ('052','BB','Barbados');
INSERT INTO country (id, code, name) VALUES ('112','BY','Belarus');
INSERT INTO country (id, code, name) VALUES ('056','BE','Belgium');
INSERT INTO country (id, code, name) VALUES ('084','BZ','Belize');
INSERT INTO country (id, code, name) VALUES ('204','BJ','Benin');
INSERT INTO country (id, code, name) VALUES ('060','BM','Bermuda');
INSERT INTO country (id, code, name) VALUES ('064','BT','Bhutan');
INSERT INTO country (id, code, name) VALUES ('068','BO','Bolivia (Plurinational State of)');
INSERT INTO country (id, code, name) VALUES ('535','BQ','Bonaire, Sint Eustatius and Saba');
INSERT INTO country (id, code, name) VALUES ('070','BA','Bosnia and Herzegovina');
INSERT INTO country (id, code, name) VALUES ('072','BW','Botswana');
INSERT INTO country (id, code, name) VALUES ('074','BV','Bouvet Island');
INSERT INTO country (id, code, name) VALUES ('076','BR','Brazil');
INSERT INTO country (id, code, name) VALUES ('086','IO','British Indian Ocean Territory');
INSERT INTO country (id, code, name) VALUES ('581','UM','United States Minor Outlying Islands');
INSERT INTO country (id, code, name) VALUES ('092','VG','Virgin Islands (British)');
INSERT INTO country (id, code, name) VALUES ('850','VI','Virgin Islands (U.S.)');
INSERT INTO country (id, code, name) VALUES ('096','BN','Brunei Darussalam');
INSERT INTO country (id, code, name) VALUES ('100','BG','Bulgaria');
INSERT INTO country (id, code, name) VALUES ('854','BF','Burkina Faso');
INSERT INTO country (id, code, name) VALUES ('108','BI','Burundi');
INSERT INTO country (id, code, name) VALUES ('116','KH','Cambodia');
INSERT INTO country (id, code, name) VALUES ('120','CM','Cameroon');
INSERT INTO country (id, code, name) VALUES ('124','CA','Canada');
INSERT INTO country (id, code, name) VALUES ('132','CV','Cabo Verde');
INSERT INTO country (id, code, name) VALUES ('136','KY','Cayman Islands');
INSERT INTO country (id, code, name) VALUES ('140','CF','Central African Republic');
INSERT INTO country (id, code, name) VALUES ('148','TD','Chad');
INSERT INTO country (id, code, name) VALUES ('152','CL','Chile');
INSERT INTO country (id, code, name) VALUES ('156','CN','China');
INSERT INTO country (id, code, name) VALUES ('162','CX','Christmas Island');
INSERT INTO country (id, code, name) VALUES ('166','CC','Cocos (Keeling) Islands');
INSERT INTO country (id, code, name) VALUES ('170','CO','Colombia');
INSERT INTO country (id, code, name) VALUES ('174','KM','Comoros');
INSERT INTO country (id, code, name) VALUES ('178','CG','Congo');
INSERT INTO country (id, code, name) VALUES ('180','CD','Congo (Democratic Republic of the)');
INSERT INTO country (id, code, name) VALUES ('184','CK','Cook Islands');
INSERT INTO country (id, code, name) VALUES ('188','CR','Costa Rica');
INSERT INTO country (id, code, name) VALUES ('191','HR','Croatia');
INSERT INTO country (id, code, name) VALUES ('192','CU','Cuba');
INSERT INTO country (id, code, name) VALUES ('531','CW','Curaçao');
INSERT INTO country (id, code, name) VALUES ('196','CY','Cyprus');
INSERT INTO country (id, code, name) VALUES ('203','CZ','Czech Republic');
INSERT INTO country (id, code, name) VALUES ('208','DK','Denmark');
INSERT INTO country (id, code, name) VALUES ('262','DJ','Djibouti');
INSERT INTO country (id, code, name) VALUES ('212','DM','Dominica');
INSERT INTO country (id, code, name) VALUES ('214','DO','Dominican Republic');
INSERT INTO country (id, code, name) VALUES ('218','EC','Ecuador');
INSERT INTO country (id, code, name) VALUES ('818','EG','Egypt');
INSERT INTO country (id, code, name) VALUES ('222','SV','El Salvador');
INSERT INTO country (id, code, name) VALUES ('226','GQ','Equatorial Guinea');
INSERT INTO country (id, code, name) VALUES ('232','ER','Eritrea');
INSERT INTO country (id, code, name) VALUES ('233','EE','Estonia');
INSERT INTO country (id, code, name) VALUES ('231','ET','Ethiopia');
INSERT INTO country (id, code, name) VALUES ('238','FK','Falkland Islands (Malvinas)');
INSERT INTO country (id, code, name) VALUES ('234','FO','Faroe Islands');
INSERT INTO country (id, code, name) VALUES ('242','FJ','Fiji');
INSERT INTO country (id, code, name) VALUES ('246','FI','Finland');
INSERT INTO country (id, code, name) VALUES ('250','FR','France');
INSERT INTO country (id, code, name) VALUES ('254','GF','French Guiana');
INSERT INTO country (id, code, name) VALUES ('258','PF','French Polynesia');
INSERT INTO country (id, code, name) VALUES ('260','TF','French Southern Territories');
INSERT INTO country (id, code, name) VALUES ('266','GA','Gabon');
INSERT INTO country (id, code, name) VALUES ('270','GM','Gambia');
INSERT INTO country (id, code, name) VALUES ('268','GE','Georgia');
INSERT INTO country (id, code, name) VALUES ('276','DE','Germany');
INSERT INTO country (id, code, name) VALUES ('288','GH','Ghana');
INSERT INTO country (id, code, name) VALUES ('292','GI','Gibraltar');
INSERT INTO country (id, code, name) VALUES ('300','GR','Greece');
INSERT INTO country (id, code, name) VALUES ('304','GL','Greenland');
INSERT INTO country (id, code, name) VALUES ('308','GD','Grenada');
INSERT INTO country (id, code, name) VALUES ('312','GP','Guadeloupe');
INSERT INTO country (id, code, name) VALUES ('316','GU','Guam');
INSERT INTO country (id, code, name) VALUES ('320','GT','Guatemala');
INSERT INTO country (id, code, name) VALUES ('831','GG','Guernsey');
INSERT INTO country (id, code, name) VALUES ('324','GN','Guinea');
INSERT INTO country (id, code, name) VALUES ('624','GW','Guinea-Bissau');
INSERT INTO country (id, code, name) VALUES ('328','GY','Guyana');
INSERT INTO country (id, code, name) VALUES ('332','HT','Haiti');
INSERT INTO country (id, code, name) VALUES ('334','HM','Heard Island and McDonald Islands');
INSERT INTO country (id, code, name) VALUES ('336','VA','Vatican City');
INSERT INTO country (id, code, name) VALUES ('340','HN','Honduras');
INSERT INTO country (id, code, name) VALUES ('348','HU','Hungary');
INSERT INTO country (id, code, name) VALUES ('344','HK','Hong Kong');
INSERT INTO country (id, code, name) VALUES ('352','IS','Iceland');
INSERT INTO country (id, code, name) VALUES ('356','IN','India');
INSERT INTO country (id, code, name) VALUES ('360','ID','Indonesia');
INSERT INTO country (id, code, name) VALUES ('384','CI','Ivory Coast');
INSERT INTO country (id, code, name) VALUES ('364','IR','Iran (Islamic Republic of)');
INSERT INTO country (id, code, name) VALUES ('368','IQ','Iraq');
INSERT INTO country (id, code, name) VALUES ('372','IE','Ireland');
INSERT INTO country (id, code, name) VALUES ('833','IM','Isle of Man');
INSERT INTO country (id, code, name) VALUES ('376','IL','Israel');
INSERT INTO country (id, code, name) VALUES ('380','IT','Italy');
INSERT INTO country (id, code, name) VALUES ('388','JM','Jamaica');
INSERT INTO country (id, code, name) VALUES ('392','JP','Japan');
INSERT INTO country (id, code, name) VALUES ('832','JE','Jersey');
INSERT INTO country (id, code, name) VALUES ('400','JO','Jordan');
INSERT INTO country (id, code, name) VALUES ('398','KZ','Kazakhstan');
INSERT INTO country (id, code, name) VALUES ('404','KE','Kenya');
INSERT INTO country (id, code, name) VALUES ('296','KI','Kiribati');
INSERT INTO country (id, code, name) VALUES ('414','KW','Kuwait');
INSERT INTO country (id, code, name) VALUES ('417','KG','Kyrgyzstan');
INSERT INTO country (id, code, name) VALUES ('418','LA','Lao People's Democratic Republic');
INSERT INTO country (id, code, name) VALUES ('428','LV','Latvia');
INSERT INTO country (id, code, name) VALUES ('422','LB','Lebanon');
INSERT INTO country (id, code, name) VALUES ('426','LS','Lesotho');
INSERT INTO country (id, code, name) VALUES ('430','LR','Liberia');
INSERT INTO country (id, code, name) VALUES ('434','LY','Libya');
INSERT INTO country (id, code, name) VALUES ('438','LI','Liechtenstein');
INSERT INTO country (id, code, name) VALUES ('440','LT','Lithuania');
INSERT INTO country (id, code, name) VALUES ('442','LU','Luxembourg');
INSERT INTO country (id, code, name) VALUES ('446','MO','Macao');
INSERT INTO country (id, code, name) VALUES ('807','MK','North Macedonia');
INSERT INTO country (id, code, name) VALUES ('450','MG','Madagascar');
INSERT INTO country (id, code, name) VALUES ('454','MW','Malawi');
INSERT INTO country (id, code, name) VALUES ('458','MY','Malaysia');
INSERT INTO country (id, code, name) VALUES ('462','MV','Maldives');
INSERT INTO country (id, code, name) VALUES ('466','ML','Mali');
INSERT INTO country (id, code, name) VALUES ('470','MT','Malta');
INSERT INTO country (id, code, name) VALUES ('584','MH','Marshall Islands');
INSERT INTO country (id, code, name) VALUES ('474','MQ','Martinique');
INSERT INTO country (id, code, name) VALUES ('478','MR','Mauritania');
INSERT INTO country (id, code, name) VALUES ('480','MU','Mauritius');
INSERT INTO country (id, code, name) VALUES ('175','YT','Mayotte');
INSERT INTO country (id, code, name) VALUES ('484','MX','Mexico');
INSERT INTO country (id, code, name) VALUES ('583','FM','Micronesia (Federated States of)');
INSERT INTO country (id, code, name) VALUES ('498','MD','Moldova (Republic of)');
INSERT INTO country (id, code, name) VALUES ('492','MC','Monaco');
INSERT INTO country (id, code, name) VALUES ('496','MN','Mongolia');
INSERT INTO country (id, code, name) VALUES ('499','ME','Montenegro');
INSERT INTO country (id, code, name) VALUES ('500','MS','Montserrat');
INSERT INTO country (id, code, name) VALUES ('504','MA','Morocco');
INSERT INTO country (id, code, name) VALUES ('508','MZ','Mozambique');
INSERT INTO country (id, code, name) VALUES ('104','MM','Myanmar');
INSERT INTO country (id, code, name) VALUES ('516','NA','Namibia');
INSERT INTO country (id, code, name) VALUES ('520','NR','Nauru');
INSERT INTO country (id, code, name) VALUES ('524','NP','Nepal');
INSERT INTO country (id, code, name) VALUES ('528','NL','Netherlands');
INSERT INTO country (id, code, name) VALUES ('540','NC','New Caledonia');
INSERT INTO country (id, code, name) VALUES ('554','NZ','New Zealand');
INSERT INTO country (id, code, name) VALUES ('558','NI','Nicaragua');
INSERT INTO country (id, code, name) VALUES ('562','NE','Niger');
INSERT INTO country (id, code, name) VALUES ('566','NG','Nigeria');
INSERT INTO country (id, code, name) VALUES ('570','NU','Niue');
INSERT INTO country (id, code, name) VALUES ('574','NF','Norfolk Island');
INSERT INTO country (id, code, name) VALUES ('408','KP','Korea (Democratic People's Republic of)');
INSERT INTO country (id, code, name) VALUES ('580','MP','Northern Mariana Islands');
INSERT INTO country (id, code, name) VALUES ('578','NO','Norway');
INSERT INTO country (id, code, name) VALUES ('512','OM','Oman');
INSERT INTO country (id, code, name) VALUES ('586','PK','Pakistan');
INSERT INTO country (id, code, name) VALUES ('585','PW','Palau');
INSERT INTO country (id, code, name) VALUES ('275','PS','Palestine, State of');
INSERT INTO country (id, code, name) VALUES ('591','PA','Panama');
INSERT INTO country (id, code, name) VALUES ('598','PG','Papua New Guinea');
INSERT INTO country (id, code, name) VALUES ('600','PY','Paraguay');
INSERT INTO country (id, code, name) VALUES ('604','PE','Peru');
INSERT INTO country (id, code, name) VALUES ('608','PH','Philippines');
INSERT INTO country (id, code, name) VALUES ('612','PN','Pitcairn');
INSERT INTO country (id, code, name) VALUES ('616','PL','Poland');
INSERT INTO country (id, code, name) VALUES ('620','PT','Portugal');
INSERT INTO country (id, code, name) VALUES ('630','PR','Puerto Rico');
INSERT INTO country (id, code, name) VALUES ('634','QA','Qatar');
INSERT INTO country (id, code, name) VALUES ('926','XK','Republic of Kosovo');
INSERT INTO country (id, code, name) VALUES ('638','RE','Réunion');
INSERT INTO country (id, code, name) VALUES ('642','RO','Romania');
INSERT INTO country (id, code, name) VALUES ('643','RU','Russian Federation');
INSERT INTO country (id, code, name) VALUES ('646','RW','Rwanda');
INSERT INTO country (id, code, name) VALUES ('652','BL','Saint Barthélemy');
INSERT INTO country (id, code, name) VALUES ('654','SH','Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country (id, code, name) VALUES ('659','KN','Saint Kitts and Nevis');
INSERT INTO country (id, code, name) VALUES ('662','LC','Saint Lucia');
INSERT INTO country (id, code, name) VALUES ('663','MF','Saint Martin (French part)');
INSERT INTO country (id, code, name) VALUES ('666','PM','Saint Pierre and Miquelon');
INSERT INTO country (id, code, name) VALUES ('670','VC','Saint Vincent and the Grenadines');
INSERT INTO country (id, code, name) VALUES ('882','WS','Samoa');
INSERT INTO country (id, code, name) VALUES ('674','SM','San Marino');
INSERT INTO country (id, code, name) VALUES ('678','ST','Sao Tome and Principe');
INSERT INTO country (id, code, name) VALUES ('682','SA','Saudi Arabia');
INSERT INTO country (id, code, name) VALUES ('686','SN','Senegal');
INSERT INTO country (id, code, name) VALUES ('688','RS','Serbia');
INSERT INTO country (id, code, name) VALUES ('690','SC','Seychelles');
INSERT INTO country (id, code, name) VALUES ('694','SL','Sierra Leone');
INSERT INTO country (id, code, name) VALUES ('702','SG','Singapore');
INSERT INTO country (id, code, name) VALUES ('534','SX','Sint Maarten (Dutch part)');
INSERT INTO country (id, code, name) VALUES ('703','SK','Slovakia');
INSERT INTO country (id, code, name) VALUES ('705','SI','Slovenia');
INSERT INTO country (id, code, name) VALUES ('090','SB','Solomon Islands');
INSERT INTO country (id, code, name) VALUES ('706','SO','Somalia');
INSERT INTO country (id, code, name) VALUES ('710','ZA','South Africa');
INSERT INTO country (id, code, name) VALUES ('239','GS','South Georgia and the South Sandwich Islands');
INSERT INTO country (id, code, name) VALUES ('410','KR','Korea (Republic of)');
INSERT INTO country (id, code, name) VALUES ('724','ES','Spain');
INSERT INTO country (id, code, name) VALUES ('144','LK','Sri Lanka');
INSERT INTO country (id, code, name) VALUES ('729','SD','Sudan');
INSERT INTO country (id, code, name) VALUES ('728','SS','South Sudan');
INSERT INTO country (id, code, name) VALUES ('740','SR','Suriname');
INSERT INTO country (id, code, name) VALUES ('744','SJ','Svalbard and Jan Mayen');
INSERT INTO country (id, code, name) VALUES ('748','SZ','Swaziland');
INSERT INTO country (id, code, name) VALUES ('752','SE','Sweden');
INSERT INTO country (id, code, name) VALUES ('756','CH','Switzerland');
INSERT INTO country (id, code, name) VALUES ('760','SY','Syrian Arab Republic');
INSERT INTO country (id, code, name) VALUES ('158','TW','Taiwan');
INSERT INTO country (id, code, name) VALUES ('762','TJ','Tajikistan');
INSERT INTO country (id, code, name) VALUES ('834','TZ','Tanzania, United Republic of');
INSERT INTO country (id, code, name) VALUES ('764','TH','Thailand');
INSERT INTO country (id, code, name) VALUES ('626','TL','Timor-Leste');
INSERT INTO country (id, code, name) VALUES ('768','TG','Togo');
INSERT INTO country (id, code, name) VALUES ('772','TK','Tokelau');
INSERT INTO country (id, code, name) VALUES ('776','TO','Tonga');
INSERT INTO country (id, code, name) VALUES ('780','TT','Trinidad and Tobago');
INSERT INTO country (id, code, name) VALUES ('788','TN','Tunisia');
INSERT INTO country (id, code, name) VALUES ('792','TR','Turkey');
INSERT INTO country (id, code, name) VALUES ('795','TM','Turkmenistan');
INSERT INTO country (id, code, name) VALUES ('796','TC','Turks and Caicos Islands');
INSERT INTO country (id, code, name) VALUES ('798','TV','Tuvalu');
INSERT INTO country (id, code, name) VALUES ('800','UG','Uganda');
INSERT INTO country (id, code, name) VALUES ('804','UA','Ukraine');
INSERT INTO country (id, code, name) VALUES ('784','AE','United Arab Emirates');
INSERT INTO country (id, code, name) VALUES ('826','GB','United Kingdom of Great Britain and Northern Ireland');
INSERT INTO country (id, code, name) VALUES ('840','US','United States of America');
INSERT INTO country (id, code, name) VALUES ('858','UY','Uruguay');
INSERT INTO country (id, code, name) VALUES ('860','UZ','Uzbekistan');
INSERT INTO country (id, code, name) VALUES ('548','VU','Vanuatu');
INSERT INTO country (id, code, name) VALUES ('862','VE','Venezuela (Bolivarian Republic of)');
INSERT INTO country (id, code, name) VALUES ('704','VN','Vietnam');
INSERT INTO country (id, code, name) VALUES ('876','WF','Wallis and Futuna');
INSERT INTO country (id, code, name) VALUES ('732','EH','Western Sahara');
INSERT INTO country (id, code, name) VALUES ('887','YE','Yemen');
INSERT INTO country (id, code, name) VALUES ('894','ZM','Zambia');
INSERT INTO country (id, code, name) VALUES ('716','ZW','Zimbabwe');
